GENERAL INFORMATION
ExperimentName,C:\Users\micromass.CORP\Desktop\Xevo DESI MS.exp
ExperimentCreationTime,Mon 01 Dec 2014 14:11:10
VersionNumber,1.0
ExperimentDuration,10000
AnalogChannelDescription1,Channel 1,Disabled
AnalogChannelDescription2,Channel 2,Disabled
AnalogChannelDescription3,Channel 3,Disabled
AnalogChannelDescription4,Channel 4,Disabled
AnalogChannelDescription5,Channel 5,Disabled
AnalogChannelDescription6,Channel 6,Disabled
AnalogChannelDescription7,Channel 7,Disabled
AnalogChannelDescription8,Channel 8,Disabled
MUXAnalogOffset1,0
MUXAnalogOffset2,0
MUXAnalogOffset3,0
MUXAnalogOffset4,0
MUXAnalogOffset5,0
MUXAnalogOffset6,0
MUXAnalogOffset7,0
MUXAnalogOffset8,0
ExperimentCalibrationFilename,c:\masslynx\default.pro\acqudb\default.cal,Enabled
ExperimentNegCalibrationFilename,,Disabled
SolventDelayStart1,0
SolventDelayEnd1,0
SolventDelayTemp1,0
SolventDelayStart2,0
SolventDelayEnd2,0
SolventDelayTemp2,0
SolventDelayStart3,0
SolventDelayEnd3,0
SolventDelayTemp3,0
SolventDelayStart4,0
SolventDelayEnd4,0
SolventDelayTemp4,0
SolventDelayDivertValveEnabled,0
ReferenceFrequency,10
ReferenceConeVoltage,40
ReferenceScanTime,1
ReferenceCentroidAverage,3
ReferenceSetMass,50
ReferenceCollisionEnergy,10
PositivePolarity,0
DREGain,100
OpticMode,0
UseMOpticMode,0
OpticModeCount,0
MultiOpticMode,1
AutoDetectorCheck,0
ProbeTemperatureRamping,0
ProbeTemperatureStart,20
ProbeTemperatureEnd,650
ProbeTemperatureIncrement,20
DREExtended,0
ExperimentExtension,TIMED_EVENTS_EXTENSION
ExperimentExtensionData,0,4,-60.000000,Flow State,LC,Sample,-60.000000,Reservoir,B,LockSpray,-60.000000,Refill,Auto-Refill,LockSpray,-60.000000,Infusion,Start,LockSpray
NumberOfFunctions,1
FunctionTypes,Tof MS

FUNCTION 1
FunctionType,Tof MS
FunctionDataFormat,Continuum
FunctionIonMode,ES Mode
FunctionPolarity,Negative
FunctionInstrumentConditions,c:\masslynx\default.pro\acqudb\default.ipr
FunctionStartMass,50
FunctionEndMass,1200
FunctionStartTime(min),0
FunctionEndTime(min),10000
FunctionScanTime(sec),0.086
FunctionInterScanTime(sec),0.014
Scans To Sum,1
Resolution,1000
PrimaryScanLock,2
SecondaryScanLock,2
ThresholdLock,100
StepLock,0.02
FunctionOnOffState,1
PeakDisplayTuneMode,0
FastDDA,0
SIRMode,Peak Top
NumSIRMasses,0
UseMOpticMode,0
OpticModeCount,1
MultiOpticMode,0
FastLockOn,1
UseOpticMode,0
RuleFile,
UseRuleFileFiltering,0
MaintainIMS,1
SaveRawEIData,0
TOFConeVoltage,40
UseTunePageConeVoltage,1
TOFProbeTemperature,550
UseTunePageProbeTemperature,1
OpticMode,0
UseCVRamp,0
CVRampInitialVoltage,40
CVRampFinalVoltage,40
SetMass,0
TargetEnhancementEnabled,0
TargetEnhancementMode,0
TargetEnhancementUsage,0
TargetEnhancementMass1,200
TargetEnhancementMass2,-1
TargetEnhancementMass3,-1
TargetEnhancementMass4,-1
TargetEnhancementMass5,-1
UseFixedCE,1
UseCEProfile,0
CEProfile01,30
CEProfile02,30
CEProfile03,30
CEProfile04,30
CEProfile05,30
CEUsage,1
UseTrapCERamp,0
UseTransferCERamp,0
TrapCERampInitialEnergy,0
TrapCERampFinalEnergy,0
TransferCERampInitialEnergy,0
TransferCERampFinalEnergy,0
UseTunePageCE,0
UseTunePageMSMSCE,1
FixedCollisionEnergy,4
UseFixedCE2,0
UseCE2Profile,0
CE2Profile01,0
CE2Profile02,0
CE2Profile03,0
CE2Profile04,0
CE2Profile05,0
CE2Usage,1
UseTunePageCE2,0
UseTunePageMSMSCE2,0
FixedCollisionEnergy2,2
UseCE2LUTMasster,0
UseCE2LUTOffset,0
FastDDATrapMSMSLowMass,100
FastDDATrapMSMSHighMass,1000
FastDDATransferMSMSLowMass,100
FastDDATransferMSMSHighMass,1000
FastDDAMSMSMassThreshold,300
FastDDAMSMSIntensityThreshold,100
FastDDAMSMSNumberOfComponents,3
FastDDAMSMScanTimeType,1
FastDDAMSMSScanTime,0.1
AcquireInMMode,0
MaldiLaserType,0
MaldiFiringRate,0
MaldiLaserEnergy,0
MaldiPlateSpeed,0
MaldiPatternFilename,
MaldiAcquisitionType,0
UseVariableFlow,0
VariableFlowPortNumber,1
VariableFlowPulseWidth,0
SwitchOnLockSpray,0
CentroidLockMass,0
CentroidAttLockMass,0
CentroidMassWindow,0.5
BaffleLock,0
TemperatureCorrection,0
TemperatureCoefficient,0
UseWizCone,0
CollisionEnergy2LUT,
CollisionEnergy1LUT,
HDCTransferLUT1,
HDCTransferLUT2,
HDCTransferLUT3,
HDCTransferLUT4,
HDCTransferLUT1Percent,100
HDCTransferLUT2Percent,0
HDCTransferLUT3Percent,0
HDCTransferLUT4Percent,0
UseAutomaticLocksprayConditions,0
CompoundName,
AttCompoundName,
LocksprayCapillaryVoltage,3
LocksprayDRESetting,99.9
CentroidLockMassOption,0
AcquireCollapsedRetentionTimeFunction,0
AcquireIMSDatatoRaw,0
MobilityTuningDREExtended,0
CentroidLockMassList,
CentroidAttLockMassList,
                       
DesiXStart,0.0
DesiYStart,0.0
DesiXLength,1.17
DesiXStep,0.025
DesiXRate,100
DesiYLength,1.2225
DesiYStep,0.025
DesiSlot,A
